version: '3.8'

services:
  db:
    image: postgres:13
    container_name: crypto_pos_db
    environment:
      POSTGRES_DB: crypto_pos_db
      POSTGRES_USER: crypto_pos_db_user
      POSTGRES_PASSWORD: crypto_pos_password_user
    ports:
      - '5432:5432' 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_pos_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres_data:
